### ISSUE TITLE
specs are missing from the published package

### ISSUE THREAD

**Issue by kirbysayshi** [mohayonao/web-audio-test-api-2#13]
Hello! When requiring this package from node, the following error appears:

```
$ node
> require('web-audio-test-api')
{ Error: Cannot find module './chrome-56'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18) code: 'MODULE_NOT_FOUND' }
>
(To exit, press ^C again or type .exit)
>
```

Inspecting the installed package shows that several files are missing:

```
$ ls -la node_modules/web-audio-test-api/lib/specs/
total 8
drwxr-xr-x  3 xxxxxx  staff   96 Feb 16 00:39 .
drwxr-xr-x  9 xxxxxx  staff  288 Feb 16 00:39 ..
-rw-r--r--  1 xxxxxx  staff  826 Feb  8  2017 index.js
```

(no specs!)

**Comment by distante** [comment]
Same problem here. I would argue that this project is not longer bein maintained.
